### ISSUE TITLE
Unable to play partial flac file such as streams

### ISSUE THREAD

**Issue by fire** [audiocogs/flac.js#14]
There was problems trying to play streamed flac files. The url works in vlc, so I was wondering if this was a working feature?

**Comment by devongovett** [comment]
Could you upload a non-working file somewhere so we can debug? Thanks!

**Comment by MorrisJobke** [comment]
I too have problems with flac supprot in 0.2.0. It's just noise (accessed over WebDAV with HTTP range request support). If I use 0.1.2 all works well.

@devongovett I can send over two files that doesn't work for me.

cc @pellaeon

ref owncloud/music#278

**Comment by devongovett** [comment]
Sounds like a bug, @MorrisJobke.  Can you send the files to devongovett at gmail dot com?  Thanks!

**Comment by MorrisJobke** [comment]
Thanks. I send you an link.

**Comment by devongovett** [comment]
@MorrisJobke should be fixed by 450bdb4263b3218b057b4301bec2cdd5d9cd6de2. There was a bug introduced in v0.2.0 in the 16-bit lpc decoding code.  Just published the fix in v0.2.1.

**Comment by MorrisJobke** [comment]
@devongovett Thanks.

**Comment by Afterster** [comment]
Isn't this should be closed or do you still have issues @MorrisJobke?

**Comment by MorrisJobke** [comment]
Works now and can be closed

**Comment by belldandu** [comment]
@fire when are you gonna close this?
