### ISSUE TITLE
FLAC files are not played with the latest version.

### ISSUE THREAD

**Issue by karamanolev** [audiocogs/flac.js#16]
I downloaded the latest releases of aurora.js and flac.js and all I can hear is very loud noise. I have also tried building them myself to the same end. I have a regular 16bit/44100hz FLAC encoded with the reference 1.2.1 encoder.
Downgrading flac.js to the previous released version fixed the issue and FLACs are being played correctly.
With the new version I verified that the decoder is registered correctly and it is used correctly.
My demo code is very simple:

```
<script src="aurora.js"></script>
<script src="flac.js"></script>
<script>
var player = AV.Player.fromURL('test.flac');
player.play();
</script>
```

**Comment by devongovett** [comment]
Should be fixed by 450bdb4. There was a bug introduced in v0.2.0 in the 16-bit lpc decoding code. Just published the fix in v0.2.1.  Please check it out and reopen the issue if it still doesn't work for you.
