### ISSUE TITLE
Mono .flac sounds like alvin and the chipmunks

### ISSUE THREAD

**Issue by kjantzer** [audiocogs/flac.js#2]
Mono .flac is played in half the time and sounds sped up.

**Comment by devongovett** [comment]
See https://github.com/ofmlabs/aurora.js/issues/9.

**Comment by devongovett** [comment]
Btw, this should be fixed now as of [this commit](https://github.com/ofmlabs/aurora.js/commit/1a8772560b30e8f77fd5044eaafe995210c05a8c) to aurora.js.  Let us know if you have further issues.  Thanks!

**Comment by kjantzer** [comment]
Sweet, thanks!
