### ISSUE TITLE
Status on this project / status on native flac support

### ISSUE THREAD

**Issue by heapwolf** [audiocogs/flac.js#29]
Hi! So, this project keeps turning up as i search for ways to play flac/alac files in the browser. I've tried to get this working but haven't had any luck (electron/chrome). Is this project dead? I've been tracking this (https://bugs.chromium.org/p/chromium/issues/detail?id=217239) but it looks pretty low priority for the chrome team.

**Comment by crackofdusk** [comment]
Hello!

Can you describe what problems you are encountering with flac.js ? Is there something in the [getting started guide](https://github.com/audiocogs/aurora.js/wiki/Getting-Started) that is not clear? Thanks!

**Comment by heapwolf** [comment]
Well, the first thing that doesn't work is the example on the landing page (http://audiocogs.org/codecs/flac/). I'm on chrome latest.

**Comment by crackofdusk** [comment]
The demo on that page requires selecting a file from your computer to play. Have you done that? If a file doesn't play, try with another one.

**Comment by heapwolf** [comment]
hehe yes, i've tried several flac files, i also tried several different files with your personal project (https://github.com/crackofdusk/glitchy-space) which doesnt seem to work either, so i npm installed, browserified the code and ran the demo locally, still, no output. My speakers work fine, im on a pretty average setup, but just to be sure, i tried from two different machines, both Windows and Linux.

**Comment by crackofdusk** [comment]
That demo of mine is indeed broken in more recent browser versions (I need to update the libraries), but I can play tracks from http://audiocogs.org/codecs/flac/ just fine (Chrome 53 and Firefox 49).

What about other codecs and file formats?

In any case, it would be helpful if you made a Gist with a minimal example that reproduces the problem on your side (containing aurora.js, flac.js as you compiled them and your test page/script).

**Comment by heapwolf** [comment]
I tired mp3s and an m4a (alac), they worked fine. Maybe you could just include an example/fixture file that you think should work along with a few tests? I can add some failing tests to that probably :)

**Comment by crackofdusk** [comment]
My first search for sample files online yielded http://www.eclassical.com/pages/24-bit-faq.html We can use those as a reference.

The 16-bit test files work, the 24-bit ones do not.

**Comment by heapwolf** [comment]
Ah! 👍 that could clear up some of the confusion here. I was trying to play the 24bit versions (which is what i need). Got it, maybe just adding that to the readme or as a failing test would be great for future visitors.

**Comment by devongovett** [comment]
The demo version is super old I think. 24 bit files should work as of https://github.com/audiocogs/flac.js/commit/53e3f7c5387d1d2c672451d9b0af9e885a57366e.

**Comment by crackofdusk** [comment]
Yes, I think so too. I will fix that when I get the time.

**Comment by crackofdusk** [comment]
@0x00A The demo page now uses the latest library versions. I trust this solves your playback problems?

**Comment by heapwolf** [comment]
@crackofdusk yeah! and thanks for the quick responses. Now that i know it supports 24bit I'll actually try integrating it into my project :) 🍻

**Comment by heapwolf** [comment]
Are there tests anywhere for [using with a node buffer](https://github.com/audiocogs/aurora.js/wiki/Player-Class-Reference#-avplayerfrombufferbuffer)? When I pass a buffer to create a player, I see that `Asset` has all the correct data, but it fails with the message `No supported audio device found.`. Using the flac file from [here](http://www.eclassical.com/pages/24-bit-faq.html), nodejs latest and electron latest. Any ideas?

``` js
const AV = require('av')
require('flac.js')
const buf = fs.readFileSync('BIS1536-001-flac_24.flac')
const player = AV.Player.fromBuffer(buf)
player.play()
```

``` json
{"message":"No supported audio device found.","stack":"Error: No supported audio device found.\n    at AudioDevice.start (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/device.js:33:15)\n    at Player.startPlaying (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/player.js:201:21)\n    at Queue.<anonymous> (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/player.js:4:59)\n    at Queue.cb (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/core/events.js:51:19)\n    at Queue.EventEmitter.emit (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/core/events.js:64:12)\n    at Queue.write (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/queue.js:37:23)\n    at Asset.<anonymous> (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/queue.js:4:59)\n    at Asset.EventEmitter.emit (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/core/events.js:64:12)\n    at Class.<anonymous> (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/asset.js:190:26)\n    at Class.EventEmitter.emit (/Users/paolofragomeni/workroot/voltraco/voltra/node_modules/av/src/core/events.js:64:12)"}
```

![image](https://cloud.githubusercontent.com/assets/136109/19769191/b93bdb50-9c5a-11e6-8f5e-4ab4b38e01e5.png)

**Comment by heapwolf** [comment]
Ah, just realized you need to require the source that you want to use. Everything seems to be working perfectly now.
