### ISSUE TITLE
play remote FLAC File 

### ISSUE THREAD

**Issue by veso266** [audiocogs/flac.js#31]
Hi I would like to play this flac file: http://5.35.250.101:8000/radio700-mpx.flac but it doesn't work (with same-orogin policy turned off in chrome I get: `HEAD http://5.35.250.101:8000/radio700-mpx.flac 400 (Bad Request)`

my code is as follows: 
`<!--- Load FLAC PLAYER ----->`
`<script src="flac/aurora.js"></script>`
`<script src="flac/flac.js"></script>`
`<script>`
`var player = AV.Player.fromURL('http://5.35.250.101:8000/radio700-mpx.flac');`
`player.play();`
`</script>`

Thanks for Anwsering and Best Regards

**Comment by bradisbell** [comment]
Icecast doesn't support HEAD requests, and therefore doesn't support CORS.  There's some work being done on this, but it doesn't exist today.

In short, there is nothing you do will be able to get around this client-side.  You would need to proxy the stream server-side and set it up for CORS.
